"""Read/write the yaml format used by manus_dg5f_sota_retarget_a.

Files look like:
    /**:
      ros__parameters:
        hand_side: right
        ...

We extract / replace the inner ros__parameters dict only. Comments are
not preserved — we write a header comment with the auto-gen timestamp.
"""
from __future__ import annotations

import datetime
import os
from typing import Any, Dict

import yaml


def load_params(yaml_path: str) -> Dict[str, Any]:
    with open(yaml_path, "r") as f:
        doc = yaml.safe_load(f)
    if not isinstance(doc, dict):
        raise ValueError(f"yaml root must be a mapping: {yaml_path}")
    # Conventional shape: { '/**:': { ros__parameters: {...} } } when keys
    # already contain the colon, or { '/**': { ros__parameters: {...} } }.
    for key, val in doc.items():
        if isinstance(val, dict) and "ros__parameters" in val:
            return dict(val["ros__parameters"])
    raise ValueError(f"could not find ros__parameters in {yaml_path}")


def save_params(yaml_path: str, params: Dict[str, Any], src_path: str | None = None):
    """Write params back as a /**: ros__parameters yaml. Drops comments;
    adds a one-line auto-gen header."""
    payload = {"/**": {"ros__parameters": params}}
    text = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    # PyYAML writes "/**":; our retarget_a yamls use unquoted /**: which
    # ROS 2 also accepts. Both forms parse, leave as quoted (safer).
    header = (
        f"# Auto-generated by dg5f_calib_wizard at "
        f"{datetime.datetime.now().isoformat(timespec='seconds')}\n"
    )
    if src_path is not None:
        header += f"# Source baseline yaml: {src_path}\n"
    header += "# Edit by re-running the wizard or hand-tweak the values below.\n\n"
    os.makedirs(os.path.dirname(os.path.abspath(yaml_path)) or ".", exist_ok=True)
    with open(yaml_path, "w") as f:
        f.write(header)
        f.write(text)
